name: Run Code Generators

on:
  schedule:
    - cron:  "0 10 * * 1" # Runs "at 10 UTC every Monday" (see https://crontab.guru)
  workflow_dispatch:  # Run on manual trigger
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.22.3
          pip install pandas==1.4.2
      - name: Run API Reference Code Generator Python Script
        run: python code-generators/API-Reference-Code-Generator.py
      - name: Run Writing Algorithm API Code Generator Python Script
        run: python code-generators/Writing-Algorithm-API-Code-Generator.py
      - name: Run Alternative Datasets Code Generator Python Script
        run: python code-generators/Alternative-Datasets-Code-Generator.py
      - name: Run Fundamentals Table Code Generator Python Script
        run: python code-generators/fundamentals-table-code-generator.py
      - name: Run Future Table Code Generator Python Script
        run: python code-generators/future-table-code-generator.py
      - name: Run Supported Assets Table Code Generator Python Script
        run: python code-generators/Supported-Assets-Table-Code-Generator.py
      - name: Run Indicator Reference Code Generator Python Script
        run: python code-generators/Indicator-Reference-Code-Generator.py
      - name: Run Fred Categories Table Code Generator Python Script
        run: python code-generators/fred-categories-table-code-generator.py
      - name: Run US Energy Categories Table Code Generator Python Script
        run: python code-generators/us-energy-indicators-code-generator.py
      - name: Run Market Hour Reference Code Generator Python Script
        run: python code-generators/market-hour-code-generator.py
      - name: Run Market Hour Convertor Python Script
        run: python code-generators/market-hour-convertor.py
      - name: Run Securities Objects Table Code Generator Python Script
        run: python code-generators/security-portfolio-table-generator.py
      - name: Run Enum Table Code Generator Python Script
        run: python code-generators/enum-table-generator.py
      - name: Run Glossary Code Generator Python Script
        run: python code-generators/glossary-generator.py
      - name: Commit and Push
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit --allow-empty -m "Code Generation from code generators"
          git push
